version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ametista
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"