export const defaultCategories = [
  {
    id: 'salary',
    name: 'Salário',
    value: 'salary',
    categoryType: 'income',
  },
  {
    id: 'investments',
    name: 'Investimentos',
    value: 'investments',
    categoryType: 'income',
  },
  {
    id: 'cashback',
    name: 'Cashback',
    value: 'cashback',
    categoryType: 'income',
  },
  {
    id: 'gift',
    name: 'Presente',
    value: 'gift',
    categoryType: 'income',
  },
  {
    id: 'rewards',
    name: 'Prêmios',
    value: 'rewards',
    categoryType: 'income',
  },
  {
    id: 'loans',
    name: 'Emprestimos',
    value: 'loans',
    categoryType: 'income',
  },
  {
    id: 'others',
    name: 'Outros',
    value: 'others',
    categoryType: 'income',
  },
  {
    id: 'refuel',
    name: 'Abastecer',
    value: 'refuel',
    categoryType: 'expense',
  },
  {
    id: 'beauty',
    name: 'Beleza',
    value: 'beauty',
    categoryType: 'expense',
  },
  {
    id: 'home',
    name: 'Casa',
    value: 'home',
    categoryType: 'expense',
  },
  {
    id: 'purchases',
    name: 'Compras',
    value: 'purchases',
    categoryType: 'expense',
  },
  {
    id: 'education',
    name: 'Educação',
    value: 'education',
    categoryType: 'expense',
  },
  {
    id: 'eletronics',
    name: 'Eletrônicos',
    value: 'eletronics',
    categoryType: 'expense',
  },
  {
    id: 'general',
    name: 'Geral',
    value: 'general',
    categoryType: 'expense',
  },
  {
    id: 'investment',
    name: 'Investimentos',
    value: 'investment',
    categoryType: 'expense',
  },
  {
    id: 'game',
    name: 'Jogo',
    value: 'game',
    categoryType: 'expense',
  },
  {
    id: 'leisure',
    name: 'Lazer',
    value: 'leisure',
    categoryType: 'expense',
  },
  {
    id: 'gift',
    name: 'Presente',
    value: 'gift',
    categoryType: 'expense',
  },
  {
    id: 'restaurant',
    name: 'Restaurante',
    value: 'restaurant',
    categoryType: 'expense',
  },
  {
    id: 'health',
    name: 'Saúde',
    value: 'health',
    categoryType: 'expense',
  },
  {
    id: 'services',
    name: 'Serviços',
    value: 'services',
    categoryType: 'expense',
  },
  {
    id: 'supermarket',
    name: 'Supermercado',
    value: 'supermarket',
    categoryType: 'expense',
  },
  {
    id: 'transporte',
    name: 'Transporte',
    value: 'transporte',
    categoryType: 'expense',
  },
  {
    id: 'travel',
    name: 'Viagem',
    value: 'travel',
    categoryType: 'expense',
  },
]
